version: 1

lifecycle:
  mode: governance

governance:
  skeleton:
    source:
      repo_url: "https://gitlab.prplanit.com/PrPlanIT/StageFreight"
      path: "skeletons/gitlab/standard.yml"
      ref: "main"
      allow_floating: true

  clusters:
    - id: docker-services
      targets:
        repos:
          - "PrPlanIT/fairer-pages"
          - "PrPlanIT/oh-CI"
          - "PrPlanIT/HomeLabHD/apt-cacher-ng"
          - "PrPlanIT/HomeLabHD/prometheus-eaton-ups-exporter"
          - "PrPlanIT/HomeLabHD/sm-lickitung-gen"
      stagefreight:
        version: 1
        targets:
          preset: "preset/docker-targets.yml"
        badges:
          preset: "preset/docker-badges.yml"
        security:
          preset: "preset/security.yml"
        dependency:
          preset: "preset/dependency.yml"
        docs:
          preset: "preset/docs.yml"
        commit:
          preset: "preset/commit.yml"
        release:
          preset: "preset/release.yml"
        lint:
          preset: "preset/lint-full.yml"

    - id: docker-binary
      targets:
        repos:
          - "PrPlanIT/StageFreight"
          - "PrPlanIT/HASteward"
      stagefreight:
        version: 1
        targets:
          preset: "preset/docker-targets.yml"
        badges:
          preset: "preset/docker-badges.yml"
        security:
          preset: "preset/security.yml"
        dependency:
          preset: "preset/dependency.yml"
        docs:
          preset: "preset/docs.yml"
        commit:
          preset: "preset/commit.yml"
        release:
          preset: "preset/release.yml"
        lint:
          preset: "preset/lint-full.yml"

    - id: docker-component
      targets:
        repos:
          - "PrPlanIT/HomeLabHD/ansible"
      stagefreight:
        version: 1
        targets:
          preset: "preset/docker-targets.yml"
        badges:
          preset: "preset/docker-badges.yml"
        security:
          preset: "preset/security.yml"
        dependency:
          preset: "preset/dependency.yml"
        docs:
          preset: "preset/docs.yml"
        commit:
          preset: "preset/commit.yml"
        release:
          preset: "preset/release.yml"
        lint:
          preset: "preset/lint-full.yml"

    - id: gitops-repos
      skeleton:
        source:
          path: "skeletons/gitlab/lightweight.yml"
      targets:
        repos:
          - "SoFMeRight/dungeon"
      stagefreight:
        version: 1
        docs:
          preset: "preset/docs.yml"
        commit:
          preset: "preset/commit.yml"
        lint:
          preset: "preset/lint-full.yml"

    - id: binary-apps
      targets:
        repos:
          - "PrPlanIT/DisplayWizard"
      stagefreight:
        version: 1
        targets:
          preset: "preset/binary-targets.yml"
        security:
          preset: "preset/security.yml"
        lint:
          preset: "preset/lint-full.yml"
